-- Repair 0012, which created yavio_eraser with an authentication method that
-- does the exact opposite of what its comment claimed.
--
-- 0012 ran `CREATE USER yavio_eraser IDENTIFIED WITH no_password` on the stated
-- premise that "a user with no password cannot authenticate, so this fails
-- closed". That is true of Postgres, where the pattern came from. In ClickHouse
-- `no_password` is an authentication METHOD meaning no credential is required:
-- checkBasicAuthentication in src/Access/Authentication.cpp returns success for
-- AuthenticationType::NO_PASSWORD, carrying the upstream comment "N.B. even if
-- the password is not empty!" — so a WRONG password authenticates too. CREATE
-- USER without a HOST clause additionally defaults to HOST ANY, and the server
-- ships with allow_no_password = 1.
--
-- The real password is applied out of band by applyUserPasswords() in
-- migrate-clickhouse.ts, which skips silently when CLICKHOUSE_ERASER_PASSWORD is
-- unset. docker-compose.yml defaults that variable to empty and .env.example
-- ships it blank, so any deployment that upgraded without adding the variable to
-- its .env is left with an unauthenticated account holding ALTER DELETE on
-- default.events — one statement from erasing every tenant's events, needing no
-- credential at all. Nothing surfaces it: the dashboard falls back to the
-- CLICKHOUSE_URL user when the variable is unset, so erasure keeps working.
--
-- sha256_hash takes the digest directly rather than a password to digest, so the
-- statement below sets a credential whose preimage was never generated and is
-- not known to anyone. The account keeps its grant and stops being reachable.
-- That is what failing closed actually looks like here.
--
-- Publishing this value leaks nothing — it is a hash with no preimage, not a
-- password, and it is deliberately the same everywhere so the repair is
-- reproducible. applyUserPasswords() runs immediately after migrations and
-- replaces it with the operator's real password whenever
-- CLICKHOUSE_ERASER_PASSWORD is set; when it is not, the account simply stays
-- unusable and erasure falls back to the CLICKHOUSE_URL user, exactly as it did
-- before 0012 existed.
--
-- IF EXISTS: deployments that never ran 0012 have no user to repair, and a
-- missing user is already the fail-closed state.

ALTER USER IF EXISTS yavio_eraser
  IDENTIFIED WITH sha256_hash BY '322464e430fa3579779f1c4b82b59b559c50126dccad25f347635cc480d07a33';
